### ISSUE TITLE
如何用multipart/form-data的contentType上传图片呢

### ISSUE THREAD

**Issue by YoungXKing** [Suzhibin/ZBNetworking#10]
查看源码里 发现上传文件用的UPLOAD方法

**Comment by Suzhibin** [comment]
request.headers=@{@"Content-Type": @"multipart/form-data"};

**Comment by Suzhibin** [comment]
- 在requestWithConfig配置内 添加请求头 和调整上传请求参数，不过我手里没有该类型请求，没法试验。只能您自己调试了。

- request.headers=@{@"Content-Type": @"multipart/form-data"};

- [request addFormDataWithName:@"image[]" fileName:@"temp. jpeg" mimeType:@"multipart/form-data" fileData:fileData];

**Comment by YoungXKing** [comment]
> * 在requestWithConfig配置内 添加请求头 和调整上传请求参数，不过我手里没有该类型请求，没法试验。只能您自己调试了。
> * request.headers=@{@"Content-Type": @"multipart/form-data"};
> * [request addFormDataWithName:@"image[]" fileName:@"temp. jpeg" mimeType:@"multipart/form-data" fileData:fileData];

后端定义的接收图片的字段的是file，我试了file[]、file、image[]、image，都不行，multipart上传数据，需要拼接的body数据格式好像是固定的，昨天用原生的afnetworking解决了
