### ISSUE TITLE
能否将下面的代码融合进去？

### ISSUE THREAD

**Issue by 295060456** [Suzhibin/ZBNetworking#12]
/// 打印请求体
+(void)printRequestMessage:(NSURLSessionDataTask *)task{
    
    /*
    // 请求URL
    NSLog(@"请求URL:%@\n",task.originalRequest.URL);
    
    // 请求方式
    NSLog(@"请求方式:%@\n",task.originalRequest.HTTPMethod);
    
    // 请求头信息
    NSLog(@"请求头信息:%@\n",task.originalRequest.allHTTPHeaderFields);
    
    // 请求正文信息
    NSLog(@"请求正文信息:%@\n",[[NSString alloc] initWithData:task.originalRequest.HTTPBody encoding:NSUTF8StringEncoding]);
    */

    // 请求响应时间
    NSTimeInterval time = [[NSDate date] timeIntervalSinceDate:NSDate.date];
    NSLog(@"请求响应时间:%@\n",@(time));
    NSLog(@"\n请求URL:%@\n请求方式:%@\n请求头信息:%@\n请求正文信息:%@\n请求响应时间:%@\n",task.originalRequest.URL,task.originalRequest.HTTPMethod,task.originalRequest.allHTTPHeaderFields,[[NSString alloc] initWithData:task.originalRequest.HTTPBody encoding:NSUTF8StringEncoding],@(time));
    
}

**Comment by 295060456** [comment]
我才看到你有打印 不好意思 是我疏忽了 我大意了没有闪

**Comment by Suzhibin** [comment]
自带的打印没有你的多，你可以在 插件方法setResponseProcessHandler  方法内 自定义设置

**Comment by 295060456** [comment]
找到你说的这个方法了
![image](https://user-images.githubusercontent.com/13795605/105332267-ff6fac80-5c06-11eb-9d01-c7aa4018c5f6.png)
但是NSURLSessionDataTask * 我怎么取?

**Comment by Suzhibin** [comment]
此方法返回的 responseObject 是正文信息。还有request对象 里面也有很多请求信息包含task，都有注释。

**Comment by 295060456** [comment]
因为我在想这么一个场景。就是后台直接要我打印我的请求头，该怎么办？就是请求头的全部数据。
你有预处理机制，预处理请求、预处理响应。所以你的这个setResponseProcessHandler返回有三个数据，第一个是请求对象，一个是响应的结果，还有个是错误。我只能到这里了，具体该怎么加我就不知道了

**Comment by Suzhibin** [comment]
请求对象 的属性有请求头 ，应该满足你的需求， 你可以参考demo内的RequestTool 类的插件机制使用。公共配置和插件 在app启动之后 请求之前设置就可以。
