### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-1202该如何解决

### ISSUE THREAD

**Issue by theskyQQ** [Suzhibin/ZBNetworking#13]
Error Domain=NSURLErrorDomain Code=-1202证书不被信任的时候该如何设置

**Comment by Suzhibin** [comment]
这个应该是请求HTTPS时证书无效造成的，解决办法就是允许使用无效的证书。
在公共配置时或者在所有请求前设置 [ZBRequestEngine defaultEngine].securityPolicy.allowInvalidCertificates = YES;
如果你是自己创建证书 参考Demo 里的 RequestTool类的最下面 证书设置
