### ISSUE TITLE
userInfo 这个NSDictionary 建议用model来进行替换管理

### ISSUE THREAD

**Issue by 295060456** [Suzhibin/ZBNetworking#17]
/**
 *  当前请求的信息，可以用来区分具有相同上下文的请求
 */
@property (nonatomic,strong,nullable) NSDictionary *userInfo;

**Comment by Suzhibin** [comment]
@295060456 多谢支持，提出宝贵建议，关于userInfo  如果是我自己app开发可能会改成model，但是选择开源出来，model的属性 不一定能满足大家的业务需求，NSDictionary 更自由一些。

**Comment by 295060456** [comment]
在我开发过程中，我遇到的很大的一个困惑就是，也许是经常需求变更带来的比如某一个单一的值改变，那么我就需要牵一发动全身。我高仿苹果新建一个类UIViewModel,集合成数据束来进行管理。后来又抽象成协议。下面附上代码：

[BaseProtocol.zip](https://github.com/Suzhibin/ZBNetworking/files/7886653/BaseProtocol.zip)
[相关Model.zip](https://github.com/Suzhibin/ZBNetworking/files/7886663/Model.zip)

这样的写法能迅速的减少无关代码，增强可变可复用性
