### ISSUE TITLE
建议URL处理一下，因为零宽空格不可见。我吃了亏

### ISSUE THREAD

**Issue by 295060456** [Suzhibin/ZBNetworking#18]
/**
 问题：直接其他地方复制过来的中文字进行网页搜索、或者中文字识别排序等情况的，会出现搜索不到的情况。
 解决方法：可能存在复制源里面的文字带了空白url编码%E2%80%8B，空白编码没有宽度，虽然看不到但是会影响结果无法正确匹配对应的中文字。可以把文字重新url编码即可。
 */
-(NSString *)urlProtect{
    if ([self containsString:@"\u200B"]) {
        return [self stringByReplacingOccurrencesOfString:@"\u200B" withString:@""];
    }else return self;
}

**Comment by Suzhibin** [comment]
嗯 你可以 在插件setRequestProcessHandler 内进行 url 加工过滤，这样所有请求的url都会受到保护。

**Comment by Suzhibin** [comment]
嗯 你可以 在插件setRequestProcessHandler 内进行 url 加工过滤，这样所有请求的url都会受到保护。

**Comment by Suzhibin** [comment]
嗯 你可以 在插件setRequestProcessHandler 内进行 url 加工过滤，
插件可以在AppDelegate 调用一次就可以 这样所有请求的url都会受到保护。demo 里的RequestTool类参考
//插件 预处理 请求
    [ZBRequestManager setRequestProcessHandler:^(ZBURLRequest * _Nullable request, id  _Nullable __autoreleasing * _Nullable setObject) {
        request.url=@"www.baidu.com";// url加工过滤
}];

**Comment by Suzhibin** [comment]
@295060456 嗯 你可以 在插件setRequestProcessHandler 内进行 url 加工过滤，
插件可以在AppDelegate 调用一次就可以 这样所有请求的url都会受到保护。demo 里的RequestTool类参考
//插件 预处理 请求
[ZBRequestManager setRequestProcessHandler:^(ZBURLRequest * _Nullable request, id _Nullable __autoreleasing * _Nullable setObject) {
request.url=@"www.baidu.com";// url加工过滤
}];
