### ISSUE TITLE
设置了header 返回400,后台提示缺少参数

### ISSUE THREAD

**Issue by guochao285575** [Suzhibin/ZBNetworking#2]
## 直接使用AFN请求,是可以的

```
    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    [manager.requestSerializer setValue:@"Basic NmJfYXBwOg==" forHTTPHeaderField:@"authorization"];
    NSDictionary *params = @{@"username": @"13800010001", @"password": @"11111111", @"grant_type" : @"password"};
    [manager POST:@"http://39.104.78.86:6060/oauth/token" parameters:params progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        NSLog(@"%@",responseObject);
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@"%@",error);
    }];
```

## 用作者框架请求,400错误,后台说少了`grant_type`参数,代码如下

```
   [ZBRequestManager requestWithConfig:^(ZBURLRequest *request){
       request.URLString=@"http://39.104.78.86:6060/oauth/token";
       request.methodType = ZBMethodTypePOST;
       request.apiType = ZBRequestTypeRefresh;
       [request setValue:@"Basic NmJfYXBwOg==" forHeaderField:@"authorization"];
       request.parameters = @{@"username": @"13800010001", @"password": @"11111111", @"grant_type" : @"password"};
    }  success:^(id responseObject,apiType type){
        NSDictionary *dataDict = [NSJSONSerialization JSONObjectWithData:responseObject options:NSJSONReadingMutableContainers error:nil];
        NSLog(@"%@",dataDict);
    } failure:^(NSError *error){
        NSLog(@"%@",error);
        if (error.code==NSURLErrorCancelled)return;
        if (error.code==NSURLErrorTimedOut){
            [self alertTitle:@"请求超时" andMessage:@""];
        }else{
            [self alertTitle:@"请求失败" andMessage:@""];
        }
    }finished:^(id responseObject, apiType type, NSError *error, BOOL isCache) {
        if (isCache==YES) {
            NSLog(@"使用了缓存");self.title=@"使用了缓存";
        }else{
            NSLog(@"重新请求");self.title=@"重新请求";
        }
    }];
}
```

**Comment by Suzhibin** [comment]
没有找到 带请求头的接口，无法调试。 你先在请求头前 设置请求格式 试试  request.requestSerializerType = ZBHTTPRequestSerializer;

**Comment by guochao285575** [comment]
request.requestSerializerType = ZBHTTPRequestSerializer;
加了之后是可以的,可以讲解一下下吗?

**Comment by guochao285575** [comment]
还有个问题,如果可以控制本次请求要不要缓存就更完美了...

**Comment by Suzhibin** [comment]
1.request.requestSerializerType = ZBHTTPRequestSerializer;  就是改变请求上传参数的格式 最终就是下面这个方法
   manager.requestSerializer=[AFHTTPRequestSerializer serializer]

2.request.apiType   就是决定你使用不使用缓存的  ， 你可以把请求封装到一个方法了    传apitype  来控制
 [self requestWithapiType:ZBRequestTypeRefresh];不使用缓存
 [self requestWithapiType:ZBRequestTypeCache];使用缓存

- (voew)requestWithapiType:(apiType)requestType{
[ZBRequestManager requestWithConfig:^(ZBURLRequest *request){
       request.URLString=@"http://39.104.78.86:6060/oauth/token";
       request.methodType = ZBMethodTypePOST;
       request.apiType = requestType;
      request.requestSerializerType = ZBHTTPRequestSerializer;
       [request setValue:@"Basic NmJfYXBwOg==" forHeaderField:@"authorization"];
       request.parameters = @{@"username": @"13800010001", @"password": @"11111111", @"grant_type" : @"password"};
    }  success:^(id responseObject,apiType type){
        NSDictionary *dataDict = [NSJSONSerialization JSONObjectWithData:responseObject options:NSJSONReadingMutableContainers error:nil];
        NSLog(@"%@",dataDict);
    } failure:^(NSError *error){
        NSLog(@"%@",error);
        if (error.code==NSURLErrorCancelled)return;
        if (error.code==NSURLErrorTimedOut){
            [self alertTitle:@"请求超时" andMessage:@""];
        }else{
            [self alertTitle:@"请求失败" andMessage:@""];
        }
    }finished:^(id responseObject, apiType type, NSError *error, BOOL isCache) {
        if (isCache==YES) {
            NSLog(@"使用了缓存");self.title=@"使用了缓存";
        }else{
            NSLog(@"重新请求");self.title=@"重新请求";
        }
    }];
}

**Comment by guochao285575** [comment]
哦, 我的意思是控制要不要缓存,而不是 使不使用缓存,现在默认的是每个请求都缓存了吧

**Comment by Suzhibin** [comment]
是的 只要是请求就会缓存下来   这也没有什么 缓存的文件很小很小
