### ISSUE TITLE
该框架没有考虑设置请求体问题吗？

### ISSUE THREAD

**Issue by StarkDuan** [Suzhibin/ZBNetworking#20]
我看了一遍代码，发现没有设置请求体的方法（setHTTPBody:），大佬是不是考虑优化一下呢

**Comment by Suzhibin** [comment]
如果要直接调用setHTTPBody，需要使用AFURLSessionManager，
   NSMutableURLRequest *request = [[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:@"url" parameters:nil error:nil];
    [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    [request setValue:@"application/json" forHTTPHeaderField:@"Accept"];
    NSData *jsonData = [NSJSONSerialization dataWithJSONObject:parameters
       options:0
         error:&error];
    NSString *jsonString = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
    [request setHTTPBody:[jsonString dataUsingEncoding:NSUTF8StringEncoding]]；
    [[ZBRequestEngine defaultEngine] dataTaskWithRequest:req uploadProgress:^(NSProgress * _Nonnull uploadProgress) {          
    } downloadProgress:^(NSProgress * _Nonnull downloadProgress) {   
    } completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
    }];
类似这种代码，但是不知道 你看没看过AFNetworking的源码，我们正常使用AFHTTPSessionManager请求的URL，Headers，parameters  最终会转成NSData，添加到HTTPBody中，所以AFNetworking 已经做了相关工作。有兴趣你可以 在AFNetworking搜索requestBySerializingRequest，看下。如果有请求不成功其实应该调一下  ContentType，headers ，Serializer 等配置是否正确。而非直接调用setHTTPBody，这样还不如不使用AFNetworking，而直接调用系统的NSURLSession post请求。
