### ISSUE TITLE
设置证书验证，程序崩溃

### ISSUE THREAD

**Issue by GongHongORzm** [Suzhibin/ZBNetworking#21]
Thread 1: "A security policy configured with `AFSSLPinningModeCertificate` can only be applied on a manager with a secure base URL (i.e. https)"

具体代码：
    
    /**
     证书设置
     ZBRequestEngine 继承AFHTTPSessionManager，所需其他设置 可以使用[ZBRequestEngine defaultEngine] 自行设置
     */
    NSString *name = @"client";
    if (name.length>0) {
        // 先导入证书
        NSString *cerPath = [[NSBundle mainBundle] pathForResource:name ofType:@"cer"];//证书的路径
        NSData *cerData = [NSData dataWithContentsOfFile:cerPath];
        AFSecurityPolicy *securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
        // 如果需要验证自建证书(无效证书)，需要设置为YES，默认为NO;
        securityPolicy.allowInvalidCertificates = YES;
        // 是否需要验证域名，默认为YES;
        securityPolicy.validatesDomainName = NO;
        securityPolicy.pinnedCertificates = [[NSSet alloc] initWithObjects:cerData, nil];
        [ZBRequestEngine defaultEngine].securityPolicy = securityPolicy;
    }
    
大佬看到后，可以设置自签名证书尝试复现这个问题。

**Comment by Suzhibin** [comment]
NSURL *url=[NSURL URLWithString:url_server];
    [[ZBRequestEngine defaultEngine]initWithBaseURL:url];
在导入证书之前 设置下BaseURL 试试
@GongHongORzm

**Comment by Suzhibin** [comment]
NSURL *url=[NSURL URLWithString:url_server];
[[ZBRequestEngine defaultEngine]initWithBaseURL:url];
在导入证书之前 设置下BaseURL 试试，另外要确保你的 BaseURL 是https 的。
@GongHongORzm

**Comment by Suzhibin** [comment]
NSURL *url=[NSURL URLWithString:url_server];
[[AFHTTPSessionManager manager]initWithBaseURL:url]

必须设置[[AFHTTPSessionManager manager]initWithBaseURL:url]，BaseURL必须为https，不要使用 ZBRequestEngine调用initWithBaseURL 会重置ZBRequestEngine内设置
   // ⚠️⚠️⚠️ 如果设置 [[AFHTTPSessionManager manager]initWithBaseURL:url] 必须在 [ZBRequestEngine defaultEngine] 之前调用，否则会重置ZBRequestEngine内设置

**Comment by GongHongORzm** [comment]
好的，已经解决了，感谢大佬！


| |
龚洪
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年07月29日 ***@***.***> 写道：

NSURL *url=[NSURL URLWithString:url_server];
[[AFHTTPSessionManager manager]initWithBaseURL:url]

必须设置[[AFHTTPSessionManager manager]initWithBaseURL:url]，BaseURL必须为https，不要使用 ZBRequestEngine调用initWithBaseURL 会重置ZBRequestEngine内设置
// ⚠️⚠️⚠️ 如果设置 [[AFHTTPSessionManager manager]initWithBaseURL:url] 必须在 [ZBRequestEngine defaultEngine] 之前调用，否则会重置ZBRequestEngine内设置
