### ISSUE TITLE
+ (void)cancelRequest:(NSUInteger)identifier; 这个方法好像没有效果

### ISSUE THREAD

**Issue by PPLLock** [Suzhibin/ZBNetworking#23]
您好，不好意思再次与你联系，我测试发现这个方法，比如设置request.identifier=3000， 在其他类里调用cancelRequest:3000好像并不能取消这个请求，请求还是会继续，有空帮忙看看

**Comment by Suzhibin** [comment]
> 您好，不好意思再次与你联系，我测试发现这个方法，比如设置request.identifier=3000， 在其他类里调用cancelRequest:3000好像并不能取消这个请求，请求还是会继续，有空帮忙看看

我试了是没问题的。request.identifier 不需要你设置，只有发起请求会自动分配，你只负责接收和给cancelRequest 传值

**Comment by PPLLock** [comment]
是这样，我在发起请求时设置request.identifier=3000为了在取消时，能取消对应的这个请求，我看文档方法介绍是通过identifier取消单个请求，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Suzhibin/ZBNetworking"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Suzhibin/ZBNetworking] + (void)cancelRequest:(NSUInteger)identifier; 这个方法好像没有效果 (Issue #23)





  
您好，不好意思再次与你联系，我测试发现这个方法，比如设置request.identifier=3000， 在其他类里调用cancelRequest:3000好像并不能取消这个请求，请求还是会继续，有空帮忙看看
  
我试了是没问题的。request.identifier 不需要你设置，只有发起请求会自动分配，你只负责接收和给cancelRequest 传值

**Comment by Suzhibin** [comment]
> 是这样，我在发起请求时设置request.identifier=3000为了在取消时，能取消对应的这个请求，我看文档方法介绍是通过identifier取消单个请求，感谢
> […](#)

嗯，是我没有写清楚，我会完善下文案，identifier 不可主动设置

**Comment by PPLLock** [comment]
抱歉兄弟，还有个问题是这样，我不知道要怎么处理好，当上一个请求很慢，然后用户切换到下一个请求，然后上一个请求数据回来了，这时候这个请求赋值就会有问题，我这边是对应每个请求数据回来后会保存数据然后在需要的地方读取，用户可能快速点击去触发多个请求



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月10日(星期四) 下午4:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Suzhibin/ZBNetworking] + (void)cancelRequest:(NSUInteger)identifier; 这个方法好像没有效果 (Issue #23)





  
是这样，我在发起请求时设置request.identifier=3000为了在取消时，能取消对应的这个请求，我看文档方法介绍是通过identifier取消单个请求，感谢
 …
  
嗯，是我没有写清楚，我会完善下文案，identifier 不可主动设置

**Comment by Suzhibin** [comment]
> 抱歉兄弟，还有个问题是这样，我不知道要怎么处理好，当上一个请求很慢，然后用户切换到下一个请求，然后上一个请求数据回来了，这时候这个请求赋值就会有问题，我这边是对应每个请求数据回来后会保存数据然后在需要的地方读取，用户可能快速点击去触发多个请求
> […](#)

request.apiType 有两个模式ZBRequestTypeKeepFirst，ZBRequestTypeKeepLast。看看是否能满足你的需求 ，可以在我的demo里的 MethodViewController类 查看例子。
注意⚠️ 请求使用keep功能 要使用parameters。不要把参数拼接在url后，有可能会因为参数变动 导致url不一样无法取消请求

**Comment by PPLLock** [comment]
好的，感谢我试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月11日(星期五) 上午9:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Suzhibin/ZBNetworking] + (void)cancelRequest:(NSUInteger)identifier; 这个方法好像没有效果 (Issue #23)





  
抱歉兄弟，还有个问题是这样，我不知道要怎么处理好，当上一个请求很慢，然后用户切换到下一个请求，然后上一个请求数据回来了，这时候这个请求赋值就会有问题，我这边是对应每个请求数据回来后会保存数据然后在需要的地方读取，用户可能快速点击去触发多个请求
 …
  
request.apiType 有两个模式ZBRequestTypeKeepFirst，ZBRequestTypeKeepLast。看看是否能满足你的需求 ，可以在我的demo里的 MethodViewController类 查看例子。
 注意⚠️ 请求使用keep功能 要使用parameters。不要把参数拼接在url后，有可能会因为参数变动 导致url不一样无法取消请求
