### ISSUE TITLE
问一下，打出的测试包找不到主机域名，但是直接连接Xcode运行的却可以。是怎么回事？

### ISSUE THREAD

**Issue by OYforQX** [Suzhibin/ZBNetworking#28]

**Comment by Suzhibin** [comment]
这个可能性有点多  
可以排查下 是否DNS的问题， 测试机的网络连接 比如wifi 切移动网络试试。
也可以在工程里排查下 打包和xcode运行 是否配置不同的build方式，即  debug 和release ，看看接口域名是否根据debug 和release    进行了不同的配置。
@OYforQX

**Comment by OYforQX** [comment]
万分感谢！
