### ISSUE TITLE
post请求直接传递json数据

### ISSUE THREAD

**Issue by guochao285575** [Suzhibin/ZBNetworking#3]
如题,项目中有的post请求是  要求直接给个json,请问目前框架可以实现不?如果不能,作者可以给个思路吗?

**Comment by Suzhibin** [comment]
post 请求 parameters 传递json    

 [ZBRequestManager requestWithConfig:^(ZBURLRequest *request){
        request.URLString=@“ URL”；
        request.methodType=ZBMethodTypePOST;
       request.requestSerializerType==ZBJSONRequestSerializer
        request.parameters=@{
               @"platformId": @"225",
              @"timezone"  : @"Asia/Shanghai"};
    }success:nil failure:nil];
