### ISSUE TITLE
设置content-type并没有生效

### ISSUE THREAD

**Issue by guochao285575** [Suzhibin/ZBNetworking#4]
- 如图,post请求,json参数形式,后台一直给我报错.设置了content-type貌似没起到作用

![image](https://user-images.githubusercontent.com/16434139/43530384-ff47a202-95df-11e8-88a1-d8c05c9f82f4.png)

**Comment by guochao285575** [comment]
用postman测试,是没有问题的

**Comment by Suzhibin** [comment]
forHeaderField 这个方法是添加请求头的方法 ，并不是改变传输格式的。建议你下载最新代码,request.requestSerializerType=ZBJSONRequestSerializer  应该就可以了

**Comment by guochao285575** [comment]
不是框架的问题,刚才跟后台对接,后台哥哥说,参数要的是字符串,这种情况我该怎么传呢?直接给request.parameters=字符串,肯定是不行的

**Comment by guochao285575** [comment]
试了,框架里面遍历了parameters,报错了,我再想想别的办法
