### ISSUE TITLE
如何在body添加参数

### ISSUE THREAD

**Issue by H4AER** [Suzhibin/ZBNetworking#9]

**Comment by Suzhibin** [comment]
ZBNetworking 是基于 AFHTTPSessionManager 的  ，而 传body参数  AF是在AFURLSessionManager 操作的，

**Comment by Suzhibin** [comment]
ZBNetworking 是基于 AFHTTPSessionManager 的 ，而 传body参数 AF是在AFURLSessionManager 操作的，这个在后续版本中在做兼容。你可以先使用AFURLSessionManager，代码大约如下

**Comment by Suzhibin** [comment]
ZBNetworking 是基于 AFHTTPSessionManager 的 ，而 传body参数 AF是在AFURLSessionManager 操作的，这个在后续版本中在做兼容。你可以先使用AFURLSessionManager，代码大约如下  AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];

    NSMutableURLRequest *request = [[AFJSONRequestSerializer serializer] requestWithMethod:method URLString:url parameters:nil error:nil];
 NSData *jsonData = [NSJSONSerialization dataWithJSONObject:params options:0 error:&error];
    NSString *jsonString = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
    [request setHTTPBody:[jsonString dataUsingEncoding:NSUTF8StringEncoding]];

    [[manager dataTaskWithRequest:request uploadProgress:^(NSProgress * _Nonnull uploadProgress) {
    } downloadProgress:^(NSProgress * _Nonnull downloadProgress) {
    } completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
        if (!error) {
            NSLog(@"Reply JSON: %@", responseObject);
        } else {
            NSLog(@"Error: %@, %@, %@", error, response, responseObject);
        }
    }] resume];
}

**Comment by H4AER** [comment]
好的，谢谢
